# use as follows:
# docker-compose -f docker-compose.prod.yml up --build
version: '3.4'
services:
  pict_api_prod:
    build:
      context: ./backend
      target: target_for_production
    environment:
      NODE_ENV: production
    container_name: pict_api_prod
    ports:
      - '8080:8080'
  # following frontend will not work because
  # browsers doe's not support CORS on localhost.
  # CORS should be disabled to test production builds on local environment.
  # https://stackoverflow.com/a/10892392/6574720
  pict_react_prod:
    image: node:12.12.0-alpine
    container_name: pict_react_prod
    environment:
      NODE_ENV: development # run frontend as dev mode to point to the local API
    volumes:
      - ./frontend:/root/frontend
      - /root/frontend/node_modules/
    working_dir: /root/frontend
    ports:
      - '3000:3000'
    command: sh -c 'yarn && yarn start'
